{{- if not .Values.postgresql.external.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "syntheticbrew-engine.fullname" . }}-secrets
  labels:
    {{- include "syntheticbrew-engine.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ include "syntheticbrew-engine.databaseURL" . | b64enc | quote }}
{{- end }}
